#
# Project: abcore
#
# Author:  Alessandro Bianco
# Website: http://alessandrobianco.eu
# Twitter: @alebianco
# Created: 19/10/2014 9.31
#

language: objective-c

git:
  depth: 1

env:
  - TERM=dumb

deploy:
  provider: releases
  api-key:
    secure: "grL8yE50lUa31ia1EZwTV9zl2Dub85LVlbQ0eIZJk4aH/vBCIca8NYmdkdCJMXa0PK55r+07x7eWLhsy/0E5e1SaM+p7DLDhMjufkmM1uHVHQYO0YJ0GrmyoAZQTtZPGMw1ifk76/eKYdhfnie9bbltLEfQC1PZ9WV4BrNkoerM="
  file: "release/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

before_install:
  - brew update >brew-update.log
  - chmod +x gradlew

install:
  - brew install caskroom/cask/brew-cask
  - brew cask install flash-player-debugger

before_script:
  - export FLASH_PLAYER_EXE="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"

script: ./gradlew release